{% set name = "opentelemetry-instrumentation-mcp" %}
{% set version = "0.46.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_mcp-{{ version }}.tar.gz
  sha256: 40172ef9eee20c774b63df64551191e94c61b54b1fe22467178cba5967e388a1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - opentelemetry-api >=1.28.0,<2.0.0
    - opentelemetry-instrumentation >=0.50b0
    - opentelemetry-semantic-conventions >=0.50b0
    - opentelemetry-semantic-conventions-ai >=0.4.12,<0.5
    - opentelemetry-exporter-otlp >=1.34.1,<2
    - mcp >=1.6.0

test:
  imports:
    - opentelemetry.instrumentation.mcp
  commands:
    - pip check
  requires:
    - mcp >=1.6.0
    - pip
    - python {{ python_min }}

about:
  home: https://www.traceloop.com/openllmetry
  summary: OpenTelemetry mcp instrumentation
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dillonroach
    - timkpaine
