{% set name = "opentelemetry-instrumentation-mcp" %}
{% set version = "0.47.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
    sha256: 4b6ba2a93932b7b3c47bc8e1174099e0087da9dda6ecaf510547d469e7b03437
  - url: https://github.com/traceloop/openllmetry/archive/refs/tags/{{ version }}.tar.gz
    sha256: 658e9ee9544ff1f6676e96bca947d9329c273620822de9a7cc5638165c59a13e
    folder: gh_src

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - poetry-core
    
  run:
    - python
    - opentelemetry-api >=1.28.0,<2.0.0
    - opentelemetry-instrumentation >=0.50b0
    - opentelemetry-semantic-conventions >=0.50b0
    - opentelemetry-semantic-conventions-ai >=0.4.13,<0.5
    - opentelemetry-exporter-otlp >=1.34.1,<2
  run_constrained:
    - mcp >=1.3.0,<2.0.0

test:
  sorce_files:
    - gh_src/packages/{{ name }}/tests
  imports:
    - opentelemetry.instrumentation.mcp
  commands:
    - pip check
    - pytest -v gh_src/packages/{{ name }}/tests
  requires:
    - pip
    - mcp >=1.3.0,<2.0.0
    - pytest >=8.2.2,<9.0.0
    - opentelemetry-sdk >=1.27.0,<2.0.0
    - pytest-asyncio

about:
  home: https://www.traceloop.com/openllmetry
  summary: OpenTelemetry mcp instrumentation
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction
  descripton: This library allows tracing of agentic workflows implemented with MCP framework mcp python sdk.
  license: Apache-2.0
  license_faily: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dillonroach
    - timkpaine
  skip-lints:
    - invalid_url
    - missing_imports_or_run_test_py
